apiVersion: v1
kind: ConfigMap
metadata:
  name: iep-config
data:
  MYSQL_DATABASE: investment_fund
  MONGO_DATABASE: investment-fund

  BLOCKCHAIN_URL: http://ganache:8545

  CONTRACT_ABI_PATH: >-
    /app/blockchain/build/InvestmentVoting.abi

  CONTRACT_BYTECODE_PATH: >-
    /app/blockchain/build/InvestmentVoting.bin

  CHECKER_RUN_ONCE: "true"
  CHECKER_INTERVAL_SECONDS: "2"
