apiVersion: v1
kind: Secret
metadata:
  name: iep-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGE_ME_MYSQL_PASSWORD

  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: CHANGE_ME_MONGO_PASSWORD

  REDIS_PASSWORD: CHANGE_ME_REDIS_PASSWORD

  JWT_SECRET_KEY: CHANGE_ME_WITH_AT_LEAST_32_RANDOM_BYTES

  DATABASE_URL: >-
    mysql+pymysql://root:CHANGE_ME_MYSQL_PASSWORD@mysql:3306/investment_fund

  MONGO_URI: >-
    mongodb://root:CHANGE_ME_MONGO_PASSWORD@mongo:27017/?authSource=admin

  REDIS_URI: >-
    redis://:CHANGE_ME_REDIS_PASSWORD@redis:6379/0
