apiVersion: batch/v1
kind: CronJob
metadata:
  name: blockchain-checker
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: blockchain-checker
        spec:
          restartPolicy: OnFailure

          containers:
            - name: blockchain-checker
              image: iep-project:v2
              imagePullPolicy: IfNotPresent
              command:
                - python
                - -m
                - services.blockchain_checker.main
              env:
                - name: CHECKER_RUN_ONCE
                  value: "false"
                - name: CHECKER_RUN_DURATION_SECONDS
                  value: "55"
              envFrom:
                - configMapRef:
                    name: iep-config
                - secretRef:
                    name: iep-secrets